### ISSUE TITLE
Potential `timeVis` adjustments to consider

### ISSUE THREAD

**Issue by aclark02-arcus** [openpharma/clinsight#98]
Many folks really like this visual!

They seem to think it would be useful to plot conmeds & procedures in their own swim lane on the `timeVis` widget too. But since there can be lots of conmeds, it may make the height of the widget really tall. And since the scope of the widget wouldn't be focused primarily on AEs, it may make sense to just move the timeline to a new tab and label it as a "patient timeline" or something similar.

Then, if a user clicks on anything in the plot, it could dynamically populate a table of data below the plot to display more info. For example, if they click on an AE, we could serve up that AE data. If they click on an conmed, it would bring in that record from the conmed listing, etc.

**Comment by LDSamson** [comment]
@aclark02-arcus closing this since it is so similar as #12. We can continue discussing `timevis` improvements in #12 .
